spring:
  application:
    name: pet
  datasource:
    url: jdbc:postgresql://localhost:5432/{TEST_DB_NAME}
    username: ${TEST_DB_USERNAME}
    password:  ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: ${TEST_PORT}

jwt:
  key:
    access: ${TEST_JWT_ACCESS_KEY}
    refresh: ${TEST_JWT_REFRESH_KEY}
  max-age:
    access: ${TEST_JWT_ACCESS_TIME}
    refresh: ${TEST_JWT_REFRESH_TIME}