spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: pet
  datasource:
    url: jdbc:postgresql://localhost:${TEST_DB_PORT}/${TEST_DB_NAME}
    username: ${TEST_DB_USERNAME}
    password:  ${TEST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: ${TEST_PORT}

jwt:
  key:
    secret: ${TEST_JWT_SECRET_KEY}
  max-age:
    access: ${TEST_JWT_ACCESS_TIME}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
